// This file was generated with `cornucopia`. Do not modify.

#[derive(Debug)]
pub struct RunParams<
    T1: crate::ArraySql<Item = uuid::Uuid>,
    T2: crate::ArraySql<Item = chrono::DateTime<chrono::Utc>>,
    T3: crate::ArraySql<Item = uuid::Uuid>,
    T4: crate::ArraySql<Item = uuid::Uuid>,
    T5: crate::ArraySql<Item = uuid::Uuid>,
    T6: crate::ArraySql<Item = uuid::Uuid>,
    T7: crate::ArraySql<Item = uuid::Uuid>,
    T8: crate::ArraySql<Item = uuid::Uuid>,
    T9: crate::StringSql,
    T10: crate::ArraySql<Item = T9>,
    T11: crate::StringSql,
    T12: crate::ArraySql<Item = T11>,
    T13: crate::StringSql,
    T14: crate::ArraySql<Item = T13>,
    T15: crate::StringSql,
    T16: crate::ArraySql<Item = T15>,
    T17: crate::ArraySql<Item = i32>,
    T18: crate::ArraySql<Item = i32>,
    T19: crate::ArraySql<Item = i32>,
    T20: crate::ArraySql<Item = i64>,
    T21: crate::ArraySql<Item = i64>,
    T22: crate::ArraySql<Item = i64>,
    T23: crate::ArraySql<Item = i64>,
    T24: crate::ArraySql<Item = i64>,
    T25: crate::ArraySql<Item = i64>,
    T26: crate::ArraySql<Item = i64>,
    T27: crate::StringSql,
    T28: crate::ArraySql<Item = T27>,
    T29: crate::ArraySql<Item = i64>,
> {
    pub p1: T1,
    pub p2: T2,
    pub p3: T3,
    pub p4: T4,
    pub p5: T5,
    pub p6: T6,
    pub p7: T7,
    pub p8: T8,
    pub p9: T10,
    pub p10: T12,
    pub p11: T14,
    pub p12: T16,
    pub p13: T17,
    pub p14: T18,
    pub p15: T19,
    pub p16: T20,
    pub p17: T21,
    pub p18: T22,
    pub p19: T23,
    pub p20: T24,
    pub p21: T25,
    pub p22: T26,
    pub p23: T28,
    pub p24: T29,
}
use crate::client::async_::GenericClient;
use futures::{self, StreamExt, TryStreamExt};
pub struct RunStmt(&'static str, Option<tokio_postgres::Statement>);
pub fn run() -> RunStmt {
    RunStmt(
        "INSERT INTO inference_requests(id,created_at,agent_id,connection_id,invocation_id,thread_id,run_id,participant_id,provider_id,kind,path,model,status,latency_ms,first_byte_ms,request_bytes,response_bytes,input_tokens,output_tokens,cached_input_tokens,cache_write_tokens,units,usage,cost_micros) SELECT u.id,u.created_at,u.agent_id,u.connection_id,u.invocation_id,u.thread_id,u.run_id,u.participant_id,u.provider_id,u.kind,u.path,NULLIF(u.model,''),u.status,u.latency_ms,NULLIF(u.first_byte_ms,-1),u.request_bytes,u.response_bytes,NULLIF(u.input_tokens,-1),NULLIF(u.output_tokens,-1),NULLIF(u.cached_input_tokens,-1),NULLIF(u.cache_write_tokens,-1),NULLIF(u.units,-1),u.usage, NULLIF(u.cost_micros,-1) FROM UNNEST($1::UUID[],$2::TIMESTAMPTZ[],$3::UUID[],$4::UUID[],$5::UUID[],$6::UUID[],$7::UUID[],$8::UUID[],$9::TEXT[],$10::TEXT[],$11::TEXT[],$12::TEXT[],$13::INTEGER[],$14::INTEGER[],$15::INTEGER[],$16::BIGINT[],$17::BIGINT[],$18::BIGINT[],$19::BIGINT[],$20::BIGINT[],$21::BIGINT[],$22::BIGINT[],$23::TEXT[],$24::BIGINT[]) AS u(id,created_at,agent_id,connection_id,invocation_id,thread_id,run_id,participant_id,provider_id,kind,path,model,status,latency_ms,first_byte_ms,request_bytes,response_bytes,input_tokens,output_tokens,cached_input_tokens,cache_write_tokens,units,usage,cost_micros) ON CONFLICT (id) DO NOTHING",
        None,
    )
}
impl RunStmt {
    pub async fn prepare<'a, C: GenericClient>(
        mut self,
        client: &'a C,
    ) -> Result<Self, tokio_postgres::Error> {
        self.1 = Some(client.prepare(self.0).await?);
        Ok(self)
    }
    pub async fn bind<
        'c,
        'a,
        's,
        C: GenericClient,
        T1: crate::ArraySql<Item = uuid::Uuid>,
        T2: crate::ArraySql<Item = chrono::DateTime<chrono::Utc>>,
        T3: crate::ArraySql<Item = uuid::Uuid>,
        T4: crate::ArraySql<Item = uuid::Uuid>,
        T5: crate::ArraySql<Item = uuid::Uuid>,
        T6: crate::ArraySql<Item = uuid::Uuid>,
        T7: crate::ArraySql<Item = uuid::Uuid>,
        T8: crate::ArraySql<Item = uuid::Uuid>,
        T9: crate::StringSql,
        T10: crate::ArraySql<Item = T9>,
        T11: crate::StringSql,
        T12: crate::ArraySql<Item = T11>,
        T13: crate::StringSql,
        T14: crate::ArraySql<Item = T13>,
        T15: crate::StringSql,
        T16: crate::ArraySql<Item = T15>,
        T17: crate::ArraySql<Item = i32>,
        T18: crate::ArraySql<Item = i32>,
        T19: crate::ArraySql<Item = i32>,
        T20: crate::ArraySql<Item = i64>,
        T21: crate::ArraySql<Item = i64>,
        T22: crate::ArraySql<Item = i64>,
        T23: crate::ArraySql<Item = i64>,
        T24: crate::ArraySql<Item = i64>,
        T25: crate::ArraySql<Item = i64>,
        T26: crate::ArraySql<Item = i64>,
        T27: crate::StringSql,
        T28: crate::ArraySql<Item = T27>,
        T29: crate::ArraySql<Item = i64>,
    >(
        &'s self,
        client: &'c C,
        p1: &'a T1,
        p2: &'a T2,
        p3: &'a T3,
        p4: &'a T4,
        p5: &'a T5,
        p6: &'a T6,
        p7: &'a T7,
        p8: &'a T8,
        p9: &'a T10,
        p10: &'a T12,
        p11: &'a T14,
        p12: &'a T16,
        p13: &'a T17,
        p14: &'a T18,
        p15: &'a T19,
        p16: &'a T20,
        p17: &'a T21,
        p18: &'a T22,
        p19: &'a T23,
        p20: &'a T24,
        p21: &'a T25,
        p22: &'a T26,
        p23: &'a T28,
        p24: &'a T29,
    ) -> Result<u64, tokio_postgres::Error> {
        client
            .execute(
                self.0,
                &[
                    p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17,
                    p18, p19, p20, p21, p22, p23, p24,
                ],
            )
            .await
    }
}
impl<
    'a,
    C: GenericClient + Send + Sync,
    T1: crate::ArraySql<Item = uuid::Uuid>,
    T2: crate::ArraySql<Item = chrono::DateTime<chrono::Utc>>,
    T3: crate::ArraySql<Item = uuid::Uuid>,
    T4: crate::ArraySql<Item = uuid::Uuid>,
    T5: crate::ArraySql<Item = uuid::Uuid>,
    T6: crate::ArraySql<Item = uuid::Uuid>,
    T7: crate::ArraySql<Item = uuid::Uuid>,
    T8: crate::ArraySql<Item = uuid::Uuid>,
    T9: crate::StringSql,
    T10: crate::ArraySql<Item = T9>,
    T11: crate::StringSql,
    T12: crate::ArraySql<Item = T11>,
    T13: crate::StringSql,
    T14: crate::ArraySql<Item = T13>,
    T15: crate::StringSql,
    T16: crate::ArraySql<Item = T15>,
    T17: crate::ArraySql<Item = i32>,
    T18: crate::ArraySql<Item = i32>,
    T19: crate::ArraySql<Item = i32>,
    T20: crate::ArraySql<Item = i64>,
    T21: crate::ArraySql<Item = i64>,
    T22: crate::ArraySql<Item = i64>,
    T23: crate::ArraySql<Item = i64>,
    T24: crate::ArraySql<Item = i64>,
    T25: crate::ArraySql<Item = i64>,
    T26: crate::ArraySql<Item = i64>,
    T27: crate::StringSql,
    T28: crate::ArraySql<Item = T27>,
    T29: crate::ArraySql<Item = i64>,
>
    crate::client::async_::Params<
        'a,
        'a,
        'a,
        RunParams<
            T1,
            T2,
            T3,
            T4,
            T5,
            T6,
            T7,
            T8,
            T9,
            T10,
            T11,
            T12,
            T13,
            T14,
            T15,
            T16,
            T17,
            T18,
            T19,
            T20,
            T21,
            T22,
            T23,
            T24,
            T25,
            T26,
            T27,
            T28,
            T29,
        >,
        std::pin::Pin<
            Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
        >,
        C,
    > for RunStmt
{
    fn params(
        &'a self,
        client: &'a C,
        params: &'a RunParams<
            T1,
            T2,
            T3,
            T4,
            T5,
            T6,
            T7,
            T8,
            T9,
            T10,
            T11,
            T12,
            T13,
            T14,
            T15,
            T16,
            T17,
            T18,
            T19,
            T20,
            T21,
            T22,
            T23,
            T24,
            T25,
            T26,
            T27,
            T28,
            T29,
        >,
    ) -> std::pin::Pin<
        Box<dyn futures::Future<Output = Result<u64, tokio_postgres::Error>> + Send + 'a>,
    > {
        Box::pin(self.bind(
            client,
            &params.p1,
            &params.p2,
            &params.p3,
            &params.p4,
            &params.p5,
            &params.p6,
            &params.p7,
            &params.p8,
            &params.p9,
            &params.p10,
            &params.p11,
            &params.p12,
            &params.p13,
            &params.p14,
            &params.p15,
            &params.p16,
            &params.p17,
            &params.p18,
            &params.p19,
            &params.p20,
            &params.p21,
            &params.p22,
            &params.p23,
            &params.p24,
        ))
    }
}
