-- Native provider credentials and caller identities are independent of management logins.
CREATE TABLE tilde_chat_keys (
 agent_id UUID PRIMARY KEY REFERENCES agents(id) ON DELETE CASCADE,
 ciphertext BYTEA NOT NULL, digest BYTEA NOT NULL
);
CREATE TABLE tilde_chat_identities (
 agent_id UUID NOT NULL REFERENCES agents(id), value TEXT NOT NULL CHECK(length(value) BETWEEN 1 AND 256),
 user_id UUID NOT NULL REFERENCES chat_users(id), PRIMARY KEY(agent_id,value), UNIQUE(agent_id,user_id)
);
CREATE TABLE tilde_chat_reads (
 thread_id UUID NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
 user_id UUID NOT NULL REFERENCES chat_users(id), sequence BIGINT NOT NULL DEFAULT 0,
 unread BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(thread_id,user_id)
);
ALTER TABLE chat_inputs ADD COLUMN queue_order BIGINT GENERATED BY DEFAULT AS IDENTITY;
UPDATE chat_inputs SET queue_order=sequence;
-- Sidecar queue snapshots survive cache eviction and lease transfer.
CREATE TABLE tilde_chat_sidecar_queue (
 thread_id UUID NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
 agent_id UUID NOT NULL REFERENCES agents(id), id UUID NOT NULL,
 invocation_id UUID NOT NULL, text TEXT NOT NULL, history_through_message_id TEXT NOT NULL,
 position BIGINT NOT NULL, PRIMARY KEY(thread_id,agent_id,id)
);
