//! PostgreSQL connections, migration history, and database errors.
//! Queries are generated by Cornucopia; domain db modules own typed operations.
use crate::error::Error;
use deadpool_postgres::{Manager, ManagerConfig, RecyclingMethod, Runtime};
use sha2::{Digest, Sha384};
use std::{str::FromStr, sync::Arc, time::Duration};
use tokio_postgres_rustls::MakeRustlsConnect;
use tokio_util::sync::CancellationToken;
pub mod db;
pub mod notifications;
pub use deadpool_postgres::{Client, Transaction};
pub use tilde_queries::client::GenericClient;

#[derive(Debug, thiserror::Error)]
pub enum DbError {
    #[error("database query failed")]
    Postgres(#[from] tokio_postgres::Error),
    #[error("database pool checkout failed")]
    Pool(#[from] deadpool_postgres::PoolError),
    #[error("database row not found")]
    NotFound,
    #[error("database row decoding failed: {0}")]
    Decode(String),
    #[error("database TLS configuration failed")]
    Tls,
}
pub type DbResult<T> = Result<T, DbError>;
impl DbError {
    pub fn decode(error: impl std::fmt::Display) -> Self {
        Self::Decode(error.to_string())
    }
    fn code(&self) -> Option<&tokio_postgres::error::SqlState> {
        match self {
            Self::Postgres(e) => e.as_db_error().map(|e| e.code()),
            Self::Pool(deadpool_postgres::PoolError::Backend(e)) => {
                e.as_db_error().map(|e| e.code())
            }
            _ => None,
        }
    }
    pub fn is_unique_violation(&self) -> bool {
        self.code() == Some(&tokio_postgres::error::SqlState::UNIQUE_VIOLATION)
    }
    pub fn is_foreign_key_violation(&self) -> bool {
        self.code() == Some(&tokio_postgres::error::SqlState::FOREIGN_KEY_VIOLATION)
    }
    pub fn is_check_violation(&self) -> bool {
        self.code() == Some(&tokio_postgres::error::SqlState::CHECK_VIOLATION)
    }
}

/// Pool identity, connection configuration and shutdown travel together. In particular,
/// each test schema and each LISTEN connection must use its own pool's configuration.
#[derive(Clone)]
pub struct Pool(Arc<PoolInner>);
struct PoolInner {
    connections: deadpool_postgres::Pool,
    config: Arc<tokio_postgres::Config>,
    closed: CancellationToken,
}
impl Pool {
    pub async fn get(&self) -> DbResult<Client> {
        Ok(self.0.connections.get().await?)
    }
    pub fn config(&self) -> Arc<tokio_postgres::Config> {
        self.0.config.clone()
    }
    pub fn is_closed(&self) -> bool {
        self.0.connections.is_closed()
    }
    pub async fn close_event(&self) {
        self.0.closed.cancelled().await
    }
    pub async fn close(&self) {
        self.0.closed.cancel();
        self.0.connections.close();
    }
}
pub(crate) fn tls() -> DbResult<MakeRustlsConnect> {
    // Match the URL's sslmode with certificate-validated TLS when the server supports it.
    static TLS: std::sync::OnceLock<MakeRustlsConnect> = std::sync::OnceLock::new();
    if let Some(tls) = TLS.get() {
        return Ok(tls.clone());
    }
    let certificates = rustls_native_certs::load_native_certs();
    let mut roots = rustls::RootCertStore::empty();
    roots.add_parsable_certificates(certificates.certs);
    let config = rustls::ClientConfig::builder_with_provider(Arc::new(
        rustls::crypto::ring::default_provider(),
    ))
    .with_safe_default_protocol_versions()
    .map_err(|_| DbError::Tls)?
    .with_root_certificates(roots)
    .with_no_client_auth();
    let connector = MakeRustlsConnect::new(config);
    Ok(TLS.get_or_init(|| connector).clone())
}
pub fn pool(url: &str, max_size: usize) -> Result<Pool, Error> {
    let config = tokio_postgres::Config::from_str(url)
        .map_err(|_| Error::Invalid("Invalid DATABASE_URL".into()))?;
    pool_from_config(config, max_size)
}
pub fn pool_from_config(config: tokio_postgres::Config, max_size: usize) -> Result<Pool, Error> {
    let manager = Manager::from_config(
        config.clone(),
        tls()?,
        ManagerConfig {
            recycling_method: RecyclingMethod::Fast,
        },
    );
    let connections = deadpool_postgres::Pool::builder(manager)
        .max_size(max_size)
        .wait_timeout(Some(Duration::from_secs(5)))
        .create_timeout(Some(Duration::from_secs(5)))
        .runtime(Runtime::Tokio1)
        .build()
        .map_err(|_| Error::Invalid("Invalid database pool configuration".into()))?;
    Ok(Pool(Arc::new(PoolInner {
        connections,
        config: Arc::new(config),
        closed: CancellationToken::new(),
    })))
}
pub async fn connect(url: &str) -> Result<Pool, Error> {
    let pool = pool(url, 10)?;
    migrate(&pool).await?;
    Ok(pool)
}

pub struct Migration {
    pub version: i64,
    pub description: &'static str,
    pub sql: &'static str,
}
/// Every migration under `migrations/`, in version order.
pub const MIGRATIONS: &[Migration] = include!(concat!(env!("OUT_DIR"), "/migrations.rs"));

/// Used by startup and tests; migration checksums protect applied history.
pub async fn migrate(pool: &Pool) -> Result<(), Error> {
    migrate_through(pool, i64::MAX).await
}

/// Migrate under a transaction-scoped lock. Cancellation rolls back both schema
/// changes and the ledger; a pooled connection cannot retain a migration lock.
/// Existing SHA-384 checksums are kept when renaming the previous driver's ledger.
pub async fn migrate_through(pool: &Pool, through: i64) -> Result<(), Error> {
    let mut client = pool.get().await?;
    let tx = client.transaction().await?;
    tx.batch_execute(include_str!("../../../queries/_migrations/lock.sql"))
        .await?;
    tx.batch_execute(include_str!(
        "../../../queries/_migrations/history_create.sql"
    ))
    .await?;
    let rows = tx
        .query(
            include_str!("../../../queries/_migrations/history.sql"),
            &[],
        )
        .await?;
    let mut applied = std::collections::BTreeSet::new();
    for row in rows {
        let version: i64 = row.try_get("version")?;
        let checksum: Vec<u8> = row.try_get("checksum")?;
        let success: bool = row.try_get("success")?;
        let migration = MIGRATIONS
            .iter()
            .find(|m| m.version == version)
            .ok_or_else(|| Error::Migration(format!("unknown applied migration {version}")))?;
        if !success || checksum != Sha384::digest(migration.sql.as_bytes()).as_slice() {
            return Err(Error::Migration(format!(
                "migration {version} failed or was modified after it was applied"
            )));
        }
        applied.insert(version);
    }
    for migration in MIGRATIONS
        .iter()
        .filter(|m| m.version <= through && !applied.contains(&m.version))
    {
        let started = std::time::Instant::now();
        tx.batch_execute(migration.sql).await.map_err(|error| {
            Error::Migration(format!("migration {} failed: {error}", migration.version))
        })?;
        let checksum = Sha384::digest(migration.sql.as_bytes()).to_vec();
        tx.execute(
            include_str!("../../../queries/_migrations/record.sql"),
            &[
                &migration.version,
                &migration.description,
                &checksum,
                &(started.elapsed().as_nanos() as i64),
            ],
        )
        .await?;
    }
    tx.commit().await?;
    Ok(())
}

impl From<DbError> for connectrpc::ConnectError {
    fn from(error: DbError) -> Self {
        crate::error::Error::Database(error).into()
    }
}
