/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAgentAgentIdRouteRouteImport } from './routes/_app/agent/$agentId/route'
import { Route as AppAgentNewRouteImport } from './routes/_app/agent/new'
import { Route as AppAuthCallbackRouteImport } from './routes/_app/auth/callback'
import { Route as ConnectionsBrokerSetupIdRouteImport } from './routes/connections/broker/$setupId'
import { Route as AppAgentAgentIdIndexRouteImport } from './routes/_app/agent/$agentId/index'
import { Route as AppAgentAgentIdCapabilitiesRouteImport } from './routes/_app/agent/$agentId/capabilities'
import { Route as AppAgentAgentIdChatProvidersRouteImport } from './routes/_app/agent/$agentId/chat-providers'
import { Route as AppAgentAgentIdDeploymentRouteImport } from './routes/_app/agent/$agentId/deployment'
import { Route as AppAgentAgentIdIamRouteImport } from './routes/_app/agent/$agentId/iam'
import { Route as AppAgentAgentIdLogsRouteImport } from './routes/_app/agent/$agentId/logs'
import { Route as AppAgentAgentIdTracingRouteImport } from './routes/_app/agent/$agentId/tracing'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentAgentIdRouteRoute = AppAgentAgentIdRouteRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentNewRoute = AppAgentNewRouteImport.update({
  id: '/agent/new',
  path: '/agent/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthCallbackRoute = AppAuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => AppRouteRoute,
} as any)
const ConnectionsBrokerSetupIdRoute =
  ConnectionsBrokerSetupIdRouteImport.update({
    id: '/connections/broker/$setupId',
    path: '/connections/broker/$setupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgentAgentIdIndexRoute = AppAgentAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdCapabilitiesRoute =
  AppAgentAgentIdCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdChatProvidersRoute =
  AppAgentAgentIdChatProvidersRouteImport.update({
    id: '/chat-providers',
    path: '/chat-providers',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdDeploymentRoute =
  AppAgentAgentIdDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdIamRoute = AppAgentAgentIdIamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdLogsRoute = AppAgentAgentIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdTracingRoute = AppAgentAgentIdTracingRouteImport.update({
  id: '/tracing',
  path: '/tracing',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agent/$agentId': typeof AppAgentAgentIdRouteRouteWithChildren
  '/agent/new': typeof AppAgentNewRoute
  '/auth/callback': typeof AppAuthCallbackRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/agent/new': typeof AppAgentNewRoute
  '/auth/callback': typeof AppAuthCallbackRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/agent/$agentId': typeof AppAgentAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/agent/$agentId': typeof AppAgentAgentIdRouteRouteWithChildren
  '/_app/agent/new': typeof AppAgentNewRoute
  '/_app/auth/callback': typeof AppAuthCallbackRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/_app/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/_app/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/_app/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/_app/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/_app/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/_app/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/_app/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent/$agentId'
    | '/agent/new'
    | '/auth/callback'
    | '/connections/broker/$setupId'
    | '/agent/$agentId/capabilities'
    | '/agent/$agentId/chat-providers'
    | '/agent/$agentId/deployment'
    | '/agent/$agentId/iam'
    | '/agent/$agentId/logs'
    | '/agent/$agentId/tracing'
    | '/agent/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent/new'
    | '/auth/callback'
    | '/connections/broker/$setupId'
    | '/agent/$agentId/capabilities'
    | '/agent/$agentId/chat-providers'
    | '/agent/$agentId/deployment'
    | '/agent/$agentId/iam'
    | '/agent/$agentId/logs'
    | '/agent/$agentId/tracing'
    | '/agent/$agentId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/agent/$agentId'
    | '/_app/agent/new'
    | '/_app/auth/callback'
    | '/connections/broker/$setupId'
    | '/_app/agent/$agentId/capabilities'
    | '/_app/agent/$agentId/chat-providers'
    | '/_app/agent/$agentId/deployment'
    | '/_app/agent/$agentId/iam'
    | '/_app/agent/$agentId/logs'
    | '/_app/agent/$agentId/tracing'
    | '/_app/agent/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ConnectionsBrokerSetupIdRoute: typeof ConnectionsBrokerSetupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agent/$agentId': {
      id: '/_app/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AppAgentAgentIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agent/new': {
      id: '/_app/agent/new'
      path: '/agent/new'
      fullPath: '/agent/new'
      preLoaderRoute: typeof AppAgentNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/auth/callback': {
      id: '/_app/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AppAuthCallbackRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/connections/broker/$setupId': {
      id: '/connections/broker/$setupId'
      path: '/connections/broker/$setupId'
      fullPath: '/connections/broker/$setupId'
      preLoaderRoute: typeof ConnectionsBrokerSetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agent/$agentId/': {
      id: '/_app/agent/$agentId/'
      path: '/'
      fullPath: '/agent/$agentId/'
      preLoaderRoute: typeof AppAgentAgentIdIndexRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/capabilities': {
      id: '/_app/agent/$agentId/capabilities'
      path: '/capabilities'
      fullPath: '/agent/$agentId/capabilities'
      preLoaderRoute: typeof AppAgentAgentIdCapabilitiesRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/chat-providers': {
      id: '/_app/agent/$agentId/chat-providers'
      path: '/chat-providers'
      fullPath: '/agent/$agentId/chat-providers'
      preLoaderRoute: typeof AppAgentAgentIdChatProvidersRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/deployment': {
      id: '/_app/agent/$agentId/deployment'
      path: '/deployment'
      fullPath: '/agent/$agentId/deployment'
      preLoaderRoute: typeof AppAgentAgentIdDeploymentRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/iam': {
      id: '/_app/agent/$agentId/iam'
      path: '/iam'
      fullPath: '/agent/$agentId/iam'
      preLoaderRoute: typeof AppAgentAgentIdIamRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/logs': {
      id: '/_app/agent/$agentId/logs'
      path: '/logs'
      fullPath: '/agent/$agentId/logs'
      preLoaderRoute: typeof AppAgentAgentIdLogsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/tracing': {
      id: '/_app/agent/$agentId/tracing'
      path: '/tracing'
      fullPath: '/agent/$agentId/tracing'
      preLoaderRoute: typeof AppAgentAgentIdTracingRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
  }
}

interface AppAgentAgentIdRouteRouteChildren {
  AppAgentAgentIdCapabilitiesRoute: typeof AppAgentAgentIdCapabilitiesRoute
  AppAgentAgentIdChatProvidersRoute: typeof AppAgentAgentIdChatProvidersRoute
  AppAgentAgentIdDeploymentRoute: typeof AppAgentAgentIdDeploymentRoute
  AppAgentAgentIdIamRoute: typeof AppAgentAgentIdIamRoute
  AppAgentAgentIdLogsRoute: typeof AppAgentAgentIdLogsRoute
  AppAgentAgentIdTracingRoute: typeof AppAgentAgentIdTracingRoute
  AppAgentAgentIdIndexRoute: typeof AppAgentAgentIdIndexRoute
}

const AppAgentAgentIdRouteRouteChildren: AppAgentAgentIdRouteRouteChildren = {
  AppAgentAgentIdCapabilitiesRoute: AppAgentAgentIdCapabilitiesRoute,
  AppAgentAgentIdChatProvidersRoute: AppAgentAgentIdChatProvidersRoute,
  AppAgentAgentIdDeploymentRoute: AppAgentAgentIdDeploymentRoute,
  AppAgentAgentIdIamRoute: AppAgentAgentIdIamRoute,
  AppAgentAgentIdLogsRoute: AppAgentAgentIdLogsRoute,
  AppAgentAgentIdTracingRoute: AppAgentAgentIdTracingRoute,
  AppAgentAgentIdIndexRoute: AppAgentAgentIdIndexRoute,
}

const AppAgentAgentIdRouteRouteWithChildren =
  AppAgentAgentIdRouteRoute._addFileChildren(AppAgentAgentIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAgentAgentIdRouteRoute: typeof AppAgentAgentIdRouteRouteWithChildren
  AppAgentNewRoute: typeof AppAgentNewRoute
  AppAuthCallbackRoute: typeof AppAuthCallbackRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAgentAgentIdRouteRoute: AppAgentAgentIdRouteRouteWithChildren,
  AppAgentNewRoute: AppAgentNewRoute,
  AppAuthCallbackRoute: AppAuthCallbackRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ConnectionsBrokerSetupIdRoute: ConnectionsBrokerSetupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
