/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSkillsRouteImport } from './routes/_app/skills'
import { Route as AppAgentAgentIdRouteRouteImport } from './routes/_app/agent/$agentId/route'
import { Route as AppAgentNewRouteImport } from './routes/_app/agent/new'
import { Route as AppSkillsSkillIdRouteImport } from './routes/_app/skills_.$skillId'
import { Route as AppSkillsCatalogRouteImport } from './routes/_app/skills_.catalog'
import { Route as AppToolsIndexRouteImport } from './routes/_app/tools/index'
import { Route as AppToolsToolIdRouteImport } from './routes/_app/tools/$toolId'
import { Route as AppToolsCatalogRouteImport } from './routes/_app/tools/catalog'
import { Route as AppToolsConnectionsRouteImport } from './routes/_app/tools/connections'
import { Route as AppToolsRemoteServersRouteImport } from './routes/_app/tools/remote-servers'
import { Route as ConnectionsBrokerSetupIdRouteImport } from './routes/connections/broker/$setupId'
import { Route as AppAgentAgentIdIndexRouteImport } from './routes/_app/agent/$agentId/index'
import { Route as AppAgentAgentIdCapabilitiesRouteImport } from './routes/_app/agent/$agentId/capabilities'
import { Route as AppAgentAgentIdChatProvidersRouteImport } from './routes/_app/agent/$agentId/chat-providers'
import { Route as AppAgentAgentIdDeploymentRouteImport } from './routes/_app/agent/$agentId/deployment'
import { Route as AppAgentAgentIdIamRouteImport } from './routes/_app/agent/$agentId/iam'
import { Route as AppAgentAgentIdInferenceRouteImport } from './routes/_app/agent/$agentId/inference'
import { Route as AppAgentAgentIdLogsRouteImport } from './routes/_app/agent/$agentId/logs'
import { Route as AppAgentAgentIdPromptsRouteImport } from './routes/_app/agent/$agentId/prompts'
import { Route as AppAgentAgentIdRoutinesRouteImport } from './routes/_app/agent/$agentId/routines'
import { Route as AppAgentAgentIdSessionsRouteImport } from './routes/_app/agent/$agentId/sessions'
import { Route as AppAgentAgentIdSkillsRouteImport } from './routes/_app/agent/$agentId/skills'
import { Route as AppAgentAgentIdToolsRouteImport } from './routes/_app/agent/$agentId/tools'
import { Route as AppAgentAgentIdTracingRouteImport } from './routes/_app/agent/$agentId/tracing'
import { Route as AppSkillsCatalogGroupIdRouteImport } from './routes/_app/skills_.catalog.$groupId'
import { Route as AppSkillsSourcesSourceIdRouteImport } from './routes/_app/skills_.sources.$sourceId'
import { Route as AppToolsCatalogProviderIdRouteImport } from './routes/_app/tools/catalog.$providerId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentAgentIdRouteRoute = AppAgentAgentIdRouteRouteImport.update({
  id: '/agent/$agentId',
  path: '/agent/$agentId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAgentNewRoute = AppAgentNewRouteImport.update({
  id: '/agent/new',
  path: '/agent/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkillsSkillIdRoute = AppSkillsSkillIdRouteImport.update({
  id: '/skills_/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSkillsCatalogRoute = AppSkillsCatalogRouteImport.update({
  id: '/skills_/catalog',
  path: '/skills/catalog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsIndexRoute = AppToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsToolIdRoute = AppToolsToolIdRouteImport.update({
  id: '/tools/$toolId',
  path: '/tools/$toolId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsCatalogRoute = AppToolsCatalogRouteImport.update({
  id: '/tools/catalog',
  path: '/tools/catalog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsConnectionsRoute = AppToolsConnectionsRouteImport.update({
  id: '/tools/connections',
  path: '/tools/connections',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppToolsRemoteServersRoute = AppToolsRemoteServersRouteImport.update({
  id: '/tools/remote-servers',
  path: '/tools/remote-servers',
  getParentRoute: () => AppRouteRoute,
} as any)
const ConnectionsBrokerSetupIdRoute =
  ConnectionsBrokerSetupIdRouteImport.update({
    id: '/connections/broker/$setupId',
    path: '/connections/broker/$setupId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgentAgentIdIndexRoute = AppAgentAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdCapabilitiesRoute =
  AppAgentAgentIdCapabilitiesRouteImport.update({
    id: '/capabilities',
    path: '/capabilities',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdChatProvidersRoute =
  AppAgentAgentIdChatProvidersRouteImport.update({
    id: '/chat-providers',
    path: '/chat-providers',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdDeploymentRoute =
  AppAgentAgentIdDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdIamRoute = AppAgentAgentIdIamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdInferenceRoute =
  AppAgentAgentIdInferenceRouteImport.update({
    id: '/inference',
    path: '/inference',
    getParentRoute: () => AppAgentAgentIdRouteRoute,
  } as any)
const AppAgentAgentIdLogsRoute = AppAgentAgentIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdPromptsRoute = AppAgentAgentIdPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdRoutinesRoute = AppAgentAgentIdRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdSessionsRoute = AppAgentAgentIdSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdSkillsRoute = AppAgentAgentIdSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdToolsRoute = AppAgentAgentIdToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppAgentAgentIdTracingRoute = AppAgentAgentIdTracingRouteImport.update({
  id: '/tracing',
  path: '/tracing',
  getParentRoute: () => AppAgentAgentIdRouteRoute,
} as any)
const AppSkillsCatalogGroupIdRoute = AppSkillsCatalogGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppSkillsCatalogRoute,
} as any)
const AppSkillsSourcesSourceIdRoute =
  AppSkillsSourcesSourceIdRouteImport.update({
    id: '/skills_/sources/$sourceId',
    path: '/skills/sources/$sourceId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppToolsCatalogProviderIdRoute =
  AppToolsCatalogProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => AppToolsCatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/skills': typeof AppSkillsRoute
  '/agent/$agentId': typeof AppAgentAgentIdRouteRouteWithChildren
  '/agent/new': typeof AppAgentNewRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/skills/catalog': typeof AppSkillsCatalogRouteWithChildren
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/tools/catalog': typeof AppToolsCatalogRouteWithChildren
  '/tools/connections': typeof AppToolsConnectionsRoute
  '/tools/remote-servers': typeof AppToolsRemoteServersRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/tools/': typeof AppToolsIndexRoute
  '/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/agent/$agentId/inference': typeof AppAgentAgentIdInferenceRoute
  '/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/agent/$agentId/prompts': typeof AppAgentAgentIdPromptsRoute
  '/agent/$agentId/routines': typeof AppAgentAgentIdRoutinesRoute
  '/agent/$agentId/sessions': typeof AppAgentAgentIdSessionsRoute
  '/agent/$agentId/skills': typeof AppAgentAgentIdSkillsRoute
  '/agent/$agentId/tools': typeof AppAgentAgentIdToolsRoute
  '/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/skills/catalog/$groupId': typeof AppSkillsCatalogGroupIdRoute
  '/skills/sources/$sourceId': typeof AppSkillsSourcesSourceIdRoute
  '/tools/catalog/$providerId': typeof AppToolsCatalogProviderIdRoute
  '/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/skills': typeof AppSkillsRoute
  '/': typeof AppIndexRoute
  '/agent/new': typeof AppAgentNewRoute
  '/skills/$skillId': typeof AppSkillsSkillIdRoute
  '/skills/catalog': typeof AppSkillsCatalogRouteWithChildren
  '/tools/$toolId': typeof AppToolsToolIdRoute
  '/tools/catalog': typeof AppToolsCatalogRouteWithChildren
  '/tools/connections': typeof AppToolsConnectionsRoute
  '/tools/remote-servers': typeof AppToolsRemoteServersRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/tools': typeof AppToolsIndexRoute
  '/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/agent/$agentId/inference': typeof AppAgentAgentIdInferenceRoute
  '/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/agent/$agentId/prompts': typeof AppAgentAgentIdPromptsRoute
  '/agent/$agentId/routines': typeof AppAgentAgentIdRoutinesRoute
  '/agent/$agentId/sessions': typeof AppAgentAgentIdSessionsRoute
  '/agent/$agentId/skills': typeof AppAgentAgentIdSkillsRoute
  '/agent/$agentId/tools': typeof AppAgentAgentIdToolsRoute
  '/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/skills/catalog/$groupId': typeof AppSkillsCatalogGroupIdRoute
  '/skills/sources/$sourceId': typeof AppSkillsSourcesSourceIdRoute
  '/tools/catalog/$providerId': typeof AppToolsCatalogProviderIdRoute
  '/agent/$agentId': typeof AppAgentAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/skills': typeof AppSkillsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agent/$agentId': typeof AppAgentAgentIdRouteRouteWithChildren
  '/_app/agent/new': typeof AppAgentNewRoute
  '/_app/skills_/$skillId': typeof AppSkillsSkillIdRoute
  '/_app/skills_/catalog': typeof AppSkillsCatalogRouteWithChildren
  '/_app/tools/$toolId': typeof AppToolsToolIdRoute
  '/_app/tools/catalog': typeof AppToolsCatalogRouteWithChildren
  '/_app/tools/connections': typeof AppToolsConnectionsRoute
  '/_app/tools/remote-servers': typeof AppToolsRemoteServersRoute
  '/connections/broker/$setupId': typeof ConnectionsBrokerSetupIdRoute
  '/_app/tools/': typeof AppToolsIndexRoute
  '/_app/agent/$agentId/capabilities': typeof AppAgentAgentIdCapabilitiesRoute
  '/_app/agent/$agentId/chat-providers': typeof AppAgentAgentIdChatProvidersRoute
  '/_app/agent/$agentId/deployment': typeof AppAgentAgentIdDeploymentRoute
  '/_app/agent/$agentId/iam': typeof AppAgentAgentIdIamRoute
  '/_app/agent/$agentId/inference': typeof AppAgentAgentIdInferenceRoute
  '/_app/agent/$agentId/logs': typeof AppAgentAgentIdLogsRoute
  '/_app/agent/$agentId/prompts': typeof AppAgentAgentIdPromptsRoute
  '/_app/agent/$agentId/routines': typeof AppAgentAgentIdRoutinesRoute
  '/_app/agent/$agentId/sessions': typeof AppAgentAgentIdSessionsRoute
  '/_app/agent/$agentId/skills': typeof AppAgentAgentIdSkillsRoute
  '/_app/agent/$agentId/tools': typeof AppAgentAgentIdToolsRoute
  '/_app/agent/$agentId/tracing': typeof AppAgentAgentIdTracingRoute
  '/_app/skills_/catalog/$groupId': typeof AppSkillsCatalogGroupIdRoute
  '/_app/skills_/sources/$sourceId': typeof AppSkillsSourcesSourceIdRoute
  '/_app/tools/catalog/$providerId': typeof AppToolsCatalogProviderIdRoute
  '/_app/agent/$agentId/': typeof AppAgentAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/skills'
    | '/agent/$agentId'
    | '/agent/new'
    | '/skills/$skillId'
    | '/skills/catalog'
    | '/tools/$toolId'
    | '/tools/catalog'
    | '/tools/connections'
    | '/tools/remote-servers'
    | '/connections/broker/$setupId'
    | '/tools/'
    | '/agent/$agentId/capabilities'
    | '/agent/$agentId/chat-providers'
    | '/agent/$agentId/deployment'
    | '/agent/$agentId/iam'
    | '/agent/$agentId/inference'
    | '/agent/$agentId/logs'
    | '/agent/$agentId/prompts'
    | '/agent/$agentId/routines'
    | '/agent/$agentId/sessions'
    | '/agent/$agentId/skills'
    | '/agent/$agentId/tools'
    | '/agent/$agentId/tracing'
    | '/skills/catalog/$groupId'
    | '/skills/sources/$sourceId'
    | '/tools/catalog/$providerId'
    | '/agent/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/skills'
    | '/'
    | '/agent/new'
    | '/skills/$skillId'
    | '/skills/catalog'
    | '/tools/$toolId'
    | '/tools/catalog'
    | '/tools/connections'
    | '/tools/remote-servers'
    | '/connections/broker/$setupId'
    | '/tools'
    | '/agent/$agentId/capabilities'
    | '/agent/$agentId/chat-providers'
    | '/agent/$agentId/deployment'
    | '/agent/$agentId/iam'
    | '/agent/$agentId/inference'
    | '/agent/$agentId/logs'
    | '/agent/$agentId/prompts'
    | '/agent/$agentId/routines'
    | '/agent/$agentId/sessions'
    | '/agent/$agentId/skills'
    | '/agent/$agentId/tools'
    | '/agent/$agentId/tracing'
    | '/skills/catalog/$groupId'
    | '/skills/sources/$sourceId'
    | '/tools/catalog/$providerId'
    | '/agent/$agentId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/skills'
    | '/_app/'
    | '/_app/agent/$agentId'
    | '/_app/agent/new'
    | '/_app/skills_/$skillId'
    | '/_app/skills_/catalog'
    | '/_app/tools/$toolId'
    | '/_app/tools/catalog'
    | '/_app/tools/connections'
    | '/_app/tools/remote-servers'
    | '/connections/broker/$setupId'
    | '/_app/tools/'
    | '/_app/agent/$agentId/capabilities'
    | '/_app/agent/$agentId/chat-providers'
    | '/_app/agent/$agentId/deployment'
    | '/_app/agent/$agentId/iam'
    | '/_app/agent/$agentId/inference'
    | '/_app/agent/$agentId/logs'
    | '/_app/agent/$agentId/prompts'
    | '/_app/agent/$agentId/routines'
    | '/_app/agent/$agentId/sessions'
    | '/_app/agent/$agentId/skills'
    | '/_app/agent/$agentId/tools'
    | '/_app/agent/$agentId/tracing'
    | '/_app/skills_/catalog/$groupId'
    | '/_app/skills_/sources/$sourceId'
    | '/_app/tools/catalog/$providerId'
    | '/_app/agent/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ConnectionsBrokerSetupIdRoute: typeof ConnectionsBrokerSetupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skills': {
      id: '/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agent/$agentId': {
      id: '/_app/agent/$agentId'
      path: '/agent/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AppAgentAgentIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/agent/new': {
      id: '/_app/agent/new'
      path: '/agent/new'
      fullPath: '/agent/new'
      preLoaderRoute: typeof AppAgentNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skills_/$skillId': {
      id: '/_app/skills_/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AppSkillsSkillIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/skills_/catalog': {
      id: '/_app/skills_/catalog'
      path: '/skills/catalog'
      fullPath: '/skills/catalog'
      preLoaderRoute: typeof AppSkillsCatalogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/': {
      id: '/_app/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AppToolsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/$toolId': {
      id: '/_app/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof AppToolsToolIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/catalog': {
      id: '/_app/tools/catalog'
      path: '/tools/catalog'
      fullPath: '/tools/catalog'
      preLoaderRoute: typeof AppToolsCatalogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/connections': {
      id: '/_app/tools/connections'
      path: '/tools/connections'
      fullPath: '/tools/connections'
      preLoaderRoute: typeof AppToolsConnectionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/remote-servers': {
      id: '/_app/tools/remote-servers'
      path: '/tools/remote-servers'
      fullPath: '/tools/remote-servers'
      preLoaderRoute: typeof AppToolsRemoteServersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/connections/broker/$setupId': {
      id: '/connections/broker/$setupId'
      path: '/connections/broker/$setupId'
      fullPath: '/connections/broker/$setupId'
      preLoaderRoute: typeof ConnectionsBrokerSetupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agent/$agentId/': {
      id: '/_app/agent/$agentId/'
      path: '/'
      fullPath: '/agent/$agentId/'
      preLoaderRoute: typeof AppAgentAgentIdIndexRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/capabilities': {
      id: '/_app/agent/$agentId/capabilities'
      path: '/capabilities'
      fullPath: '/agent/$agentId/capabilities'
      preLoaderRoute: typeof AppAgentAgentIdCapabilitiesRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/chat-providers': {
      id: '/_app/agent/$agentId/chat-providers'
      path: '/chat-providers'
      fullPath: '/agent/$agentId/chat-providers'
      preLoaderRoute: typeof AppAgentAgentIdChatProvidersRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/deployment': {
      id: '/_app/agent/$agentId/deployment'
      path: '/deployment'
      fullPath: '/agent/$agentId/deployment'
      preLoaderRoute: typeof AppAgentAgentIdDeploymentRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/iam': {
      id: '/_app/agent/$agentId/iam'
      path: '/iam'
      fullPath: '/agent/$agentId/iam'
      preLoaderRoute: typeof AppAgentAgentIdIamRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/inference': {
      id: '/_app/agent/$agentId/inference'
      path: '/inference'
      fullPath: '/agent/$agentId/inference'
      preLoaderRoute: typeof AppAgentAgentIdInferenceRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/logs': {
      id: '/_app/agent/$agentId/logs'
      path: '/logs'
      fullPath: '/agent/$agentId/logs'
      preLoaderRoute: typeof AppAgentAgentIdLogsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/prompts': {
      id: '/_app/agent/$agentId/prompts'
      path: '/prompts'
      fullPath: '/agent/$agentId/prompts'
      preLoaderRoute: typeof AppAgentAgentIdPromptsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/routines': {
      id: '/_app/agent/$agentId/routines'
      path: '/routines'
      fullPath: '/agent/$agentId/routines'
      preLoaderRoute: typeof AppAgentAgentIdRoutinesRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/sessions': {
      id: '/_app/agent/$agentId/sessions'
      path: '/sessions'
      fullPath: '/agent/$agentId/sessions'
      preLoaderRoute: typeof AppAgentAgentIdSessionsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/skills': {
      id: '/_app/agent/$agentId/skills'
      path: '/skills'
      fullPath: '/agent/$agentId/skills'
      preLoaderRoute: typeof AppAgentAgentIdSkillsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/tools': {
      id: '/_app/agent/$agentId/tools'
      path: '/tools'
      fullPath: '/agent/$agentId/tools'
      preLoaderRoute: typeof AppAgentAgentIdToolsRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/agent/$agentId/tracing': {
      id: '/_app/agent/$agentId/tracing'
      path: '/tracing'
      fullPath: '/agent/$agentId/tracing'
      preLoaderRoute: typeof AppAgentAgentIdTracingRouteImport
      parentRoute: typeof AppAgentAgentIdRouteRoute
    }
    '/_app/skills_/catalog/$groupId': {
      id: '/_app/skills_/catalog/$groupId'
      path: '/$groupId'
      fullPath: '/skills/catalog/$groupId'
      preLoaderRoute: typeof AppSkillsCatalogGroupIdRouteImport
      parentRoute: typeof AppSkillsCatalogRoute
    }
    '/_app/skills_/sources/$sourceId': {
      id: '/_app/skills_/sources/$sourceId'
      path: '/skills/sources/$sourceId'
      fullPath: '/skills/sources/$sourceId'
      preLoaderRoute: typeof AppSkillsSourcesSourceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tools/catalog/$providerId': {
      id: '/_app/tools/catalog/$providerId'
      path: '/$providerId'
      fullPath: '/tools/catalog/$providerId'
      preLoaderRoute: typeof AppToolsCatalogProviderIdRouteImport
      parentRoute: typeof AppToolsCatalogRoute
    }
  }
}

interface AppAgentAgentIdRouteRouteChildren {
  AppAgentAgentIdCapabilitiesRoute: typeof AppAgentAgentIdCapabilitiesRoute
  AppAgentAgentIdChatProvidersRoute: typeof AppAgentAgentIdChatProvidersRoute
  AppAgentAgentIdDeploymentRoute: typeof AppAgentAgentIdDeploymentRoute
  AppAgentAgentIdIamRoute: typeof AppAgentAgentIdIamRoute
  AppAgentAgentIdInferenceRoute: typeof AppAgentAgentIdInferenceRoute
  AppAgentAgentIdLogsRoute: typeof AppAgentAgentIdLogsRoute
  AppAgentAgentIdPromptsRoute: typeof AppAgentAgentIdPromptsRoute
  AppAgentAgentIdRoutinesRoute: typeof AppAgentAgentIdRoutinesRoute
  AppAgentAgentIdSessionsRoute: typeof AppAgentAgentIdSessionsRoute
  AppAgentAgentIdSkillsRoute: typeof AppAgentAgentIdSkillsRoute
  AppAgentAgentIdToolsRoute: typeof AppAgentAgentIdToolsRoute
  AppAgentAgentIdTracingRoute: typeof AppAgentAgentIdTracingRoute
  AppAgentAgentIdIndexRoute: typeof AppAgentAgentIdIndexRoute
}

const AppAgentAgentIdRouteRouteChildren: AppAgentAgentIdRouteRouteChildren = {
  AppAgentAgentIdCapabilitiesRoute: AppAgentAgentIdCapabilitiesRoute,
  AppAgentAgentIdChatProvidersRoute: AppAgentAgentIdChatProvidersRoute,
  AppAgentAgentIdDeploymentRoute: AppAgentAgentIdDeploymentRoute,
  AppAgentAgentIdIamRoute: AppAgentAgentIdIamRoute,
  AppAgentAgentIdInferenceRoute: AppAgentAgentIdInferenceRoute,
  AppAgentAgentIdLogsRoute: AppAgentAgentIdLogsRoute,
  AppAgentAgentIdPromptsRoute: AppAgentAgentIdPromptsRoute,
  AppAgentAgentIdRoutinesRoute: AppAgentAgentIdRoutinesRoute,
  AppAgentAgentIdSessionsRoute: AppAgentAgentIdSessionsRoute,
  AppAgentAgentIdSkillsRoute: AppAgentAgentIdSkillsRoute,
  AppAgentAgentIdToolsRoute: AppAgentAgentIdToolsRoute,
  AppAgentAgentIdTracingRoute: AppAgentAgentIdTracingRoute,
  AppAgentAgentIdIndexRoute: AppAgentAgentIdIndexRoute,
}

const AppAgentAgentIdRouteRouteWithChildren =
  AppAgentAgentIdRouteRoute._addFileChildren(AppAgentAgentIdRouteRouteChildren)

interface AppSkillsCatalogRouteChildren {
  AppSkillsCatalogGroupIdRoute: typeof AppSkillsCatalogGroupIdRoute
}

const AppSkillsCatalogRouteChildren: AppSkillsCatalogRouteChildren = {
  AppSkillsCatalogGroupIdRoute: AppSkillsCatalogGroupIdRoute,
}

const AppSkillsCatalogRouteWithChildren =
  AppSkillsCatalogRoute._addFileChildren(AppSkillsCatalogRouteChildren)

interface AppToolsCatalogRouteChildren {
  AppToolsCatalogProviderIdRoute: typeof AppToolsCatalogProviderIdRoute
}

const AppToolsCatalogRouteChildren: AppToolsCatalogRouteChildren = {
  AppToolsCatalogProviderIdRoute: AppToolsCatalogProviderIdRoute,
}

const AppToolsCatalogRouteWithChildren = AppToolsCatalogRoute._addFileChildren(
  AppToolsCatalogRouteChildren,
)

interface AppRouteRouteChildren {
  AppSkillsRoute: typeof AppSkillsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentAgentIdRouteRoute: typeof AppAgentAgentIdRouteRouteWithChildren
  AppAgentNewRoute: typeof AppAgentNewRoute
  AppSkillsSkillIdRoute: typeof AppSkillsSkillIdRoute
  AppSkillsCatalogRoute: typeof AppSkillsCatalogRouteWithChildren
  AppToolsToolIdRoute: typeof AppToolsToolIdRoute
  AppToolsCatalogRoute: typeof AppToolsCatalogRouteWithChildren
  AppToolsConnectionsRoute: typeof AppToolsConnectionsRoute
  AppToolsRemoteServersRoute: typeof AppToolsRemoteServersRoute
  AppToolsIndexRoute: typeof AppToolsIndexRoute
  AppSkillsSourcesSourceIdRoute: typeof AppSkillsSourcesSourceIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSkillsRoute: AppSkillsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentAgentIdRouteRoute: AppAgentAgentIdRouteRouteWithChildren,
  AppAgentNewRoute: AppAgentNewRoute,
  AppSkillsSkillIdRoute: AppSkillsSkillIdRoute,
  AppSkillsCatalogRoute: AppSkillsCatalogRouteWithChildren,
  AppToolsToolIdRoute: AppToolsToolIdRoute,
  AppToolsCatalogRoute: AppToolsCatalogRouteWithChildren,
  AppToolsConnectionsRoute: AppToolsConnectionsRoute,
  AppToolsRemoteServersRoute: AppToolsRemoteServersRoute,
  AppToolsIndexRoute: AppToolsIndexRoute,
  AppSkillsSourcesSourceIdRoute: AppSkillsSourcesSourceIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  ConnectionsBrokerSetupIdRoute: ConnectionsBrokerSetupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
